---
# tasks file for roles/debian
- apt:
    update_cache: yes
    cache_valid_time: 84400
  tags: ['packages']

- name: Remove apt packages
  apt:
    pkg:
      - nano
    state: absent
  tags: ['packages']

- name: Install apt packages
  apt:
    pkg:
      - snapd
      - firefox
      - chromium-browser
      - filezilla
      - nginx
      - vim
      - neofetch
      - virtualbox
      - net-tools
      - docker-compose
    state: present
  tags: ['packages']

- name: Install snaps
  community.general.snap:
    name:
      - spotify
    state: present
  tags: ['packages']



- name: Install snaps in classic mode
  community.general.snap:
    state: present
    name:
      - code
      - sublime-text
    classic: yes
  tags: ['packages']

- name: Install docker dependancies 
  apt:
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  tags: ['packages']

- name: Add docker official GPG key
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: ['packages']

- name: Add the docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
  tags: ['packages']

- name: Update apt cache and install docker
  apt:
    update_cache: yes
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags: ['packages']

